### ISSUE TITLE
FileNotFoundError when reproducing the TACO example

### ISSUE THREAD

**Issue by HUSTLDL** [Meowuu7/GeneOH-Diffusion#2]
I finished the Denoising & Mesh reconstruction successfully, but when I run "python visualize/vis_taco_example_20231104_017.py" as offered, I encountered the error:

/home/ldl/.conda/envs/py38/lib/python3.8/site-packages/manopth/manolayer.py:72: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755903507/work/torch/csrc/utils/tensor_numpy.cpp:178.)
  torch.Tensor(smpl_data['betas'].r).unsqueeze(0))
Traceback (most recent call last):
  File "visualize/vis_taco_example_20231104_017.py", line 195, in <module>
    vis_predicted_joints_taco(predicted_info_fn, optimized_fn, pkl_fn)
  File "visualize/vis_taco_example_20231104_017.py", line 60, in vis_predicted_joints_taco
    data = np.load(optimized_fn, allow_pickle=True).item()
  File "/home/ldl/.conda/envs/py38/lib/python3.8/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
**FileNotFoundError: [Errno 2] No such file or directory: './data/taco/result/optimized_infos_sv_dict_seq_0_seed_0_tag_20231104_017_jts_spatial_t_100__st_0_0_jts_spatial_t_200_dist_thres_0.001_with_proj_False_wmaskanchors_multi_ntag_4.npy'**

I checked the /data/taco/recult folder and couldn't find the file as above.

**Comment by Meowuu7** [comment]
Hello,

Thank you for your attention to our work and for bringing this issue to my notice. The filenames in the visualization script are outdated. While cleaning up the code, I adopted a different `test_tag`, yet the visualization script continues to reference the old one. This is likely the reason behind the `FileNotFoundError` you encountered. I have rectified this issue in my latest commit, so it should be OK if you try it again. 

Best regards
